version: '2'
services:
  firefly-app:
    image: firefly
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://firefly-mysql:3306/firefly?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://firefly-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://firefly-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://firefly-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://firefly-elasticsearch:9200
    ports:
      - 9999:9999
  firefly-mysql:
    extends:
      file: mysql.yml
      service: firefly-mysql
  firefly-redis:
    extends:
      file: redis.yml
      service: firefly-redis
  firefly-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: firefly-elasticsearch
